/**
 * Danh mục mở rộng cho nhà thuốc: những mặt hàng hay gặp nhất ở quầy.
 *
 * Đây là **dữ liệu dùng thử**. Tên thuốc, hoạt chất, dạng bào chế và việc
 * thuốc thuộc nhóm kê đơn hay không kê đơn được ghi theo thực tế; còn giá
 * bán, giá vốn, số lô và nhà sản xuất là số liệu mẫu — nhà thuốc phải nhập
 * lại theo hóa đơn thật trước khi dùng.
 *
 * Cố ý **không** ghi số đăng ký thuốc: số đăng ký là định danh do Bộ Y tế
 * cấp, đặt số giả vào đây dễ bị hiểu nhầm là số thật.
 */

export type ExtraUnit = {
  name: string;
  conversionToBase: number;
  salePrice: number;
  isDefaultSaleUnit?: boolean;
};

export type ExtraBatch = {
  batchNumber: string;
  /** Hạn dùng tính theo số ngày kể từ hôm nay, để dữ liệu thử không bị cũ. */
  expiryInDays: number;
  unitName: string;
  quantity: number;
  unitCost: number;
};

export type ExtraProduct = {
  code: string;
  name: string;
  productType: "DRUG" | "SUPPLEMENT" | "MEDICAL_DEVICE" | "COSMETIC" | "OTHER";
  drugClass: "OTC" | "RX" | "CONTROLLED" | null;
  categoryName: string;
  dosageForm: string;
  strengthText?: string;
  packagingText: string;
  manufacturer: string;
  countryOfOrigin: string;
  storageCondition: string;
  minStockBaseQuantity: number;
  vatRatePercent: number;
  ingredients: Array<{ name: string; strengthText: string }>;
  units: ExtraUnit[];
  batches: ExtraBatch[];
};

export const EXTRA_CATEGORIES = [
  "Thuốc tim mạch, huyết áp",
  "Thuốc tiểu đường",
  "Thuốc hô hấp",
  "Thuốc da liễu",
  "Thuốc mắt, tai mũi họng",
  "Thực phẩm chức năng",
  "Chăm sóc cá nhân",
  "Vật tư y tế",
];

export const EXTRA_INGREDIENTS = [
  "Acid clavulanic",
  "Acetylcystein",
  "Amlodipin",
  "Atorvastatin",
  "Azithromycin",
  "Berberin clorid",
  "Betamethason",
  "Bisoprolol",
  "Bromhexin",
  "Caffein",
  "Calci carbonat",
  "Cefixim",
  "Cefuroxim",
  "Clorpheniramin",
  "Diosmectit",
  "Domperidon",
  "Esomeprazol",
  "Gliclazid",
  "Glucose khan",
  "Kẽm gluconat",
  "Loratadin",
  "Losartan",
  "Metformin",
  "Metronidazol",
  "Natri clorid",
  "Povidon iod",
  "Salbutamol",
  "Tobramycin",
  "Vitamin B1",
  "Vitamin B12",
  "Vitamin B6",
  "Vitamin D3",
  "Cao lá thường xuân",
  "Dầu cá Omega-3",
];

/** Giá trị dùng chung cho phần lớn mặt hàng, ghi đè khi cần. */
const base = {
  countryOfOrigin: "Việt Nam",
  storageCondition: "Nơi khô ráo, dưới 30 độ C",
  vatRatePercent: 5,
};

export const EXTRA_PRODUCTS: ExtraProduct[] = [
  // --- Giảm đau, hạ sốt (không kê đơn) -------------------------------------
  {
    ...base,
    code: "TH0010",
    name: "Efferalgan 500mg viên sủi",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc giảm đau, hạ sốt",
    dosageForm: "Viên sủi",
    strengthText: "500 mg",
    packagingText: "Hộp 4 vỉ x 4 viên",
    manufacturer: "UPSA SAS",
    countryOfOrigin: "Pháp",
    minStockBaseQuantity: 64,
    ingredients: [{ name: "Paracetamol", strengthText: "500 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 4000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 4, salePrice: 15000 },
      { name: "Hộp", conversionToBase: 16, salePrice: 58000 },
    ],
    batches: [{ batchNumber: "EF2601", expiryInDays: 540, unitName: "Hộp", quantity: 12, unitCost: 44000 }],
  },
  {
    ...base,
    code: "TH0011",
    name: "Panadol Extra",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc giảm đau, hạ sốt",
    dosageForm: "Viên nén bao phim",
    strengthText: "500 mg + 65 mg",
    packagingText: "Hộp 15 vỉ x 12 viên",
    manufacturer: "Sanofi",
    countryOfOrigin: "Việt Nam",
    minStockBaseQuantity: 240,
    ingredients: [
      { name: "Paracetamol", strengthText: "500 mg" },
      { name: "Caffein", strengthText: "65 mg" },
    ],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 2500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 12, salePrice: 28000 },
    ],
    batches: [{ batchNumber: "PE2603", expiryInDays: 720, unitName: "Vỉ", quantity: 40, unitCost: 21000 }],
  },
  {
    ...base,
    code: "TH0012",
    name: "Hapacol 250 bột sủi trẻ em",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc giảm đau, hạ sốt",
    dosageForm: "Bột pha uống",
    strengthText: "250 mg",
    packagingText: "Hộp 24 gói",
    manufacturer: "Công ty CP Dược Hậu Giang",
    minStockBaseQuantity: 96,
    ingredients: [{ name: "Paracetamol", strengthText: "250 mg" }],
    units: [
      { name: "Gói", conversionToBase: 1, salePrice: 3000, isDefaultSaleUnit: true },
      { name: "Hộp", conversionToBase: 24, salePrice: 68000 },
    ],
    batches: [{ batchNumber: "HP2602", expiryInDays: 600, unitName: "Hộp", quantity: 10, unitCost: 52000 }],
  },
  {
    ...base,
    code: "TH0013",
    name: "Alaxan",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc giảm đau, hạ sốt",
    dosageForm: "Viên nén bao phim",
    strengthText: "325 mg + 200 mg",
    packagingText: "Hộp 10 vỉ x 10 viên",
    manufacturer: "United Pharma",
    minStockBaseQuantity: 200,
    ingredients: [
      { name: "Paracetamol", strengthText: "325 mg" },
      { name: "Ibuprofen", strengthText: "200 mg" },
    ],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 3500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 33000 },
    ],
    batches: [{ batchNumber: "AL2605", expiryInDays: 660, unitName: "Vỉ", quantity: 30, unitCost: 25000 }],
  },

  // --- Kháng sinh (kê đơn) -------------------------------------------------
  {
    ...base,
    code: "TH0014",
    name: "Augmentin 625mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc kháng sinh",
    dosageForm: "Viên nén bao phim",
    strengthText: "500 mg + 125 mg",
    packagingText: "Hộp 2 vỉ x 7 viên",
    manufacturer: "GlaxoSmithKline",
    countryOfOrigin: "Anh",
    minStockBaseQuantity: 56,
    ingredients: [
      { name: "Amoxicillin", strengthText: "500 mg" },
      { name: "Acid clavulanic", strengthText: "125 mg" },
    ],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 19000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 7, salePrice: 130000 },
      { name: "Hộp", conversionToBase: 14, salePrice: 255000 },
    ],
    batches: [{ batchNumber: "AU2604", expiryInDays: 500, unitName: "Hộp", quantity: 8, unitCost: 196000 }],
  },
  {
    ...base,
    code: "TH0015",
    name: "Cefixim 200mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc kháng sinh",
    dosageForm: "Viên nang cứng",
    strengthText: "200 mg",
    packagingText: "Hộp 2 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Imexpharm",
    minStockBaseQuantity: 60,
    ingredients: [{ name: "Cefixim", strengthText: "200 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 9000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 85000 },
    ],
    batches: [{ batchNumber: "CX2601", expiryInDays: 450, unitName: "Vỉ", quantity: 20, unitCost: 64000 }],
  },
  {
    ...base,
    code: "TH0016",
    name: "Azithromycin 500mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc kháng sinh",
    dosageForm: "Viên nén bao phim",
    strengthText: "500 mg",
    packagingText: "Hộp 1 vỉ x 3 viên",
    manufacturer: "Công ty CP Dược phẩm Imexpharm",
    minStockBaseQuantity: 30,
    ingredients: [{ name: "Azithromycin", strengthText: "500 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 15000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 3, salePrice: 42000 },
    ],
    batches: [{ batchNumber: "AZ2602", expiryInDays: 480, unitName: "Vỉ", quantity: 25, unitCost: 31000 }],
  },
  {
    ...base,
    code: "TH0017",
    name: "Cefuroxim 500mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc kháng sinh",
    dosageForm: "Viên nén bao phim",
    strengthText: "500 mg",
    packagingText: "Hộp 1 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Hà Tây",
    minStockBaseQuantity: 40,
    ingredients: [{ name: "Cefuroxim", strengthText: "500 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 12000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 112000 },
    ],
    batches: [{ batchNumber: "CU2603", expiryInDays: 420, unitName: "Vỉ", quantity: 18, unitCost: 84000 }],
  },
  {
    ...base,
    code: "TH0018",
    name: "Metronidazol 250mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc kháng sinh",
    dosageForm: "Viên nén",
    strengthText: "250 mg",
    packagingText: "Hộp 10 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Khánh Hòa",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Metronidazol", strengthText: "250 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 9000 },
    ],
    batches: [{ batchNumber: "MT2601", expiryInDays: 600, unitName: "Vỉ", quantity: 40, unitCost: 6500 }],
  },

  // --- Tim mạch, huyết áp (kê đơn) ----------------------------------------
  {
    ...base,
    code: "TH0019",
    name: "Amlodipin 5mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tim mạch, huyết áp",
    dosageForm: "Viên nén",
    strengthText: "5 mg",
    packagingText: "Hộp 3 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Stella",
    minStockBaseQuantity: 300,
    ingredients: [{ name: "Amlodipin", strengthText: "5 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 14000 },
      { name: "Hộp", conversionToBase: 30, salePrice: 40000 },
    ],
    batches: [{ batchNumber: "AM2602", expiryInDays: 700, unitName: "Hộp", quantity: 20, unitCost: 30000 }],
  },
  {
    ...base,
    code: "TH0020",
    name: "Losartan 50mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tim mạch, huyết áp",
    dosageForm: "Viên nén bao phim",
    strengthText: "50 mg",
    packagingText: "Hộp 3 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Sa Vi",
    minStockBaseQuantity: 300,
    ingredients: [{ name: "Losartan", strengthText: "50 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 2500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 23000 },
      { name: "Hộp", conversionToBase: 30, salePrice: 66000 },
    ],
    batches: [{ batchNumber: "LO2601", expiryInDays: 680, unitName: "Hộp", quantity: 15, unitCost: 50000 }],
  },
  {
    ...base,
    code: "TH0021",
    name: "Atorvastatin 20mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tim mạch, huyết áp",
    dosageForm: "Viên nén bao phim",
    strengthText: "20 mg",
    packagingText: "Hộp 3 vỉ x 10 viên",
    manufacturer: "Công ty CP Pymepharco",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Atorvastatin", strengthText: "20 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 4000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 38000 },
    ],
    batches: [{ batchNumber: "AT2604", expiryInDays: 640, unitName: "Vỉ", quantity: 30, unitCost: 28000 }],
  },
  {
    ...base,
    code: "TH0022",
    name: "Bisoprolol 2.5mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tim mạch, huyết áp",
    dosageForm: "Viên nén bao phim",
    strengthText: "2,5 mg",
    packagingText: "Hộp 3 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Hà Tây",
    minStockBaseQuantity: 150,
    ingredients: [{ name: "Bisoprolol", strengthText: "2,5 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 2000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 18000 },
    ],
    batches: [{ batchNumber: "BI2603", expiryInDays: 620, unitName: "Vỉ", quantity: 25, unitCost: 13000 }],
  },

  // --- Tiểu đường (kê đơn) -------------------------------------------------
  {
    ...base,
    code: "TH0023",
    name: "Metformin 500mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tiểu đường",
    dosageForm: "Viên nén bao phim",
    strengthText: "500 mg",
    packagingText: "Hộp 5 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Sa Vi",
    minStockBaseQuantity: 300,
    ingredients: [{ name: "Metformin", strengthText: "500 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1200, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 11000 },
      { name: "Hộp", conversionToBase: 50, salePrice: 52000 },
    ],
    batches: [{ batchNumber: "ME2602", expiryInDays: 700, unitName: "Hộp", quantity: 12, unitCost: 39000 }],
  },
  {
    ...base,
    code: "TH0024",
    name: "Gliclazid MR 30mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tiểu đường",
    dosageForm: "Viên nén giải phóng chậm",
    strengthText: "30 mg",
    packagingText: "Hộp 2 vỉ x 30 viên",
    manufacturer: "Công ty CP Pymepharco",
    minStockBaseQuantity: 120,
    ingredients: [{ name: "Gliclazid", strengthText: "30 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 2200, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 30, salePrice: 62000 },
    ],
    batches: [{ batchNumber: "GL2601", expiryInDays: 560, unitName: "Vỉ", quantity: 14, unitCost: 46000 }],
  },

  // --- Tiêu hóa ------------------------------------------------------------
  {
    ...base,
    code: "TH0025",
    name: "Esomeprazol 20mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tiêu hóa",
    dosageForm: "Viên nang giải phóng chậm",
    strengthText: "20 mg",
    packagingText: "Hộp 2 vỉ x 14 viên",
    manufacturer: "Công ty CP Dược phẩm Stella",
    minStockBaseQuantity: 112,
    ingredients: [{ name: "Esomeprazol", strengthText: "20 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 4500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 14, salePrice: 60000 },
    ],
    batches: [{ batchNumber: "ES2603", expiryInDays: 520, unitName: "Vỉ", quantity: 16, unitCost: 45000 }],
  },
  {
    ...base,
    code: "TH0026",
    name: "Domperidon 10mg",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc tiêu hóa",
    dosageForm: "Viên nén",
    strengthText: "10 mg",
    packagingText: "Hộp 10 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Khánh Hòa",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Domperidon", strengthText: "10 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1000, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 9000 },
    ],
    batches: [{ batchNumber: "DO2601", expiryInDays: 580, unitName: "Vỉ", quantity: 35, unitCost: 6500 }],
  },
  {
    ...base,
    code: "TH0027",
    name: "Smecta hương cam",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc tiêu hóa",
    dosageForm: "Bột pha hỗn dịch uống",
    strengthText: "3 g",
    packagingText: "Hộp 30 gói",
    manufacturer: "Beaufour Ipsen",
    countryOfOrigin: "Pháp",
    minStockBaseQuantity: 90,
    ingredients: [{ name: "Diosmectit", strengthText: "3 g" }],
    units: [
      { name: "Gói", conversionToBase: 1, salePrice: 5000, isDefaultSaleUnit: true },
      { name: "Hộp", conversionToBase: 30, salePrice: 140000 },
    ],
    batches: [{ batchNumber: "SM2602", expiryInDays: 600, unitName: "Hộp", quantity: 10, unitCost: 106000 }],
  },
  {
    ...base,
    code: "TH0028",
    name: "Berberin 10mg",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc tiêu hóa",
    dosageForm: "Viên nén bao đường",
    strengthText: "10 mg",
    packagingText: "Lọ 100 viên",
    manufacturer: "Công ty CP Dược phẩm Nam Hà",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Berberin clorid", strengthText: "10 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 400, isDefaultSaleUnit: true },
      { name: "Lọ", conversionToBase: 100, salePrice: 35000 },
    ],
    batches: [{ batchNumber: "BE2601", expiryInDays: 660, unitName: "Lọ", quantity: 15, unitCost: 26000 }],
  },
  {
    ...base,
    code: "TH0029",
    name: "Oresol hương cam",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc tiêu hóa",
    dosageForm: "Bột pha dung dịch uống",
    packagingText: "Hộp 20 gói",
    manufacturer: "Công ty CP Dược phẩm Nam Hà",
    minStockBaseQuantity: 60,
    ingredients: [
      { name: "Natri clorid", strengthText: "0,52 g" },
      { name: "Glucose khan", strengthText: "2,7 g" },
    ],
    units: [
      { name: "Gói", conversionToBase: 1, salePrice: 3000, isDefaultSaleUnit: true },
      { name: "Hộp", conversionToBase: 20, salePrice: 55000 },
    ],
    batches: [{ batchNumber: "OR2604", expiryInDays: 500, unitName: "Hộp", quantity: 12, unitCost: 41000 }],
  },

  // --- Hô hấp --------------------------------------------------------------
  {
    ...base,
    code: "TH0031",
    name: "Ventolin 100mcg bình xịt",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc hô hấp",
    dosageForm: "Hỗn dịch xịt định liều",
    strengthText: "100 mcg/liều",
    packagingText: "Bình xịt 200 liều",
    manufacturer: "GlaxoSmithKline",
    countryOfOrigin: "Pháp",
    minStockBaseQuantity: 10,
    ingredients: [{ name: "Salbutamol", strengthText: "100 mcg" }],
    units: [{ name: "Bình", conversionToBase: 1, salePrice: 95000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "VE2602", expiryInDays: 420, unitName: "Bình", quantity: 12, unitCost: 72000 }],
  },
  {
    ...base,
    code: "TH0032",
    name: "Acetylcystein 200mg",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc hô hấp",
    dosageForm: "Thuốc bột uống",
    strengthText: "200 mg",
    packagingText: "Hộp 30 gói",
    manufacturer: "Công ty CP Dược Hậu Giang",
    minStockBaseQuantity: 90,
    ingredients: [{ name: "Acetylcystein", strengthText: "200 mg" }],
    units: [
      { name: "Gói", conversionToBase: 1, salePrice: 2500, isDefaultSaleUnit: true },
      { name: "Hộp", conversionToBase: 30, salePrice: 68000 },
    ],
    batches: [{ batchNumber: "AC2603", expiryInDays: 560, unitName: "Hộp", quantity: 10, unitCost: 50000 }],
  },
  {
    ...base,
    code: "TH0033",
    name: "Bromhexin 8mg",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc hô hấp",
    dosageForm: "Viên nén",
    strengthText: "8 mg",
    packagingText: "Hộp 5 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Khánh Hòa",
    minStockBaseQuantity: 150,
    ingredients: [{ name: "Bromhexin", strengthText: "8 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 700, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 6500 },
    ],
    batches: [{ batchNumber: "BR2601", expiryInDays: 640, unitName: "Vỉ", quantity: 40, unitCost: 4800 }],
  },
  {
    ...base,
    code: "TH0034",
    name: "Siro ho Prospan 100ml",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc hô hấp",
    dosageForm: "Siro",
    packagingText: "Chai 100 ml",
    manufacturer: "Engelhard Arzneimittel",
    countryOfOrigin: "Đức",
    minStockBaseQuantity: 15,
    ingredients: [{ name: "Cao lá thường xuân", strengthText: "7 g/100 ml" }],
    units: [{ name: "Chai", conversionToBase: 1, salePrice: 95000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "PR2605", expiryInDays: 480, unitName: "Chai", quantity: 18, unitCost: 72000 }],
  },

  // --- Dị ứng --------------------------------------------------------------
  {
    ...base,
    code: "TH0036",
    name: "Loratadin 10mg",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc dị ứng",
    dosageForm: "Viên nén",
    strengthText: "10 mg",
    packagingText: "Hộp 10 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Sa Vi",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Loratadin", strengthText: "10 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1200, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 11000 },
    ],
    batches: [{ batchNumber: "LR2602", expiryInDays: 620, unitName: "Vỉ", quantity: 35, unitCost: 8000 }],
  },
  {
    ...base,
    code: "TH0037",
    name: "Clorpheniramin 4mg",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc dị ứng",
    dosageForm: "Viên nén",
    strengthText: "4 mg",
    packagingText: "Lọ 100 viên",
    manufacturer: "Công ty CP Dược phẩm Hà Tây",
    minStockBaseQuantity: 200,
    ingredients: [{ name: "Clorpheniramin", strengthText: "4 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 300, isDefaultSaleUnit: true },
      { name: "Lọ", conversionToBase: 100, salePrice: 25000 },
    ],
    batches: [{ batchNumber: "CL2601", expiryInDays: 600, unitName: "Lọ", quantity: 12, unitCost: 18000 }],
  },

  // --- Da liễu, sát khuẩn ---------------------------------------------------
  {
    ...base,
    code: "TH0038",
    name: "Betamethason 0.05% kem bôi",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc da liễu",
    dosageForm: "Kem bôi da",
    strengthText: "0,05%",
    packagingText: "Tuýp 15 g",
    manufacturer: "Công ty CP Dược phẩm Medipharco",
    minStockBaseQuantity: 20,
    ingredients: [{ name: "Betamethason", strengthText: "0,05%" }],
    units: [{ name: "Tuýp", conversionToBase: 1, salePrice: 28000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "BM2603", expiryInDays: 500, unitName: "Tuýp", quantity: 24, unitCost: 20000 }],
  },
  {
    ...base,
    code: "TH0039",
    name: "Povidon iod 10% 20ml",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc da liễu",
    dosageForm: "Dung dịch dùng ngoài",
    strengthText: "10%",
    packagingText: "Lọ 20 ml",
    manufacturer: "Công ty CP Dược phẩm Medipharco",
    minStockBaseQuantity: 30,
    ingredients: [{ name: "Povidon iod", strengthText: "10%" }],
    units: [{ name: "Lọ", conversionToBase: 1, salePrice: 18000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "PV2601", expiryInDays: 700, unitName: "Lọ", quantity: 30, unitCost: 12000 }],
  },

  // --- Mắt, tai mũi họng ----------------------------------------------------
  {
    ...base,
    code: "TH0041",
    name: "Natri clorid 0.9% nhỏ mắt 10ml",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Thuốc mắt, tai mũi họng",
    dosageForm: "Dung dịch nhỏ mắt",
    strengthText: "0,9%",
    packagingText: "Lọ 10 ml",
    manufacturer: "Công ty CP Dược phẩm Traphaco",
    minStockBaseQuantity: 60,
    ingredients: [{ name: "Natri clorid", strengthText: "0,9%" }],
    units: [{ name: "Lọ", conversionToBase: 1, salePrice: 5000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "NA2602", expiryInDays: 540, unitName: "Lọ", quantity: 80, unitCost: 3200 }],
  },
  {
    ...base,
    code: "TH0042",
    name: "Tobramycin 0.3% nhỏ mắt",
    productType: "DRUG",
    drugClass: "RX",
    categoryName: "Thuốc mắt, tai mũi họng",
    dosageForm: "Dung dịch nhỏ mắt",
    strengthText: "0,3%",
    packagingText: "Lọ 5 ml",
    manufacturer: "Công ty CP Dược phẩm Hà Nội",
    minStockBaseQuantity: 20,
    ingredients: [{ name: "Tobramycin", strengthText: "0,3%" }],
    units: [{ name: "Lọ", conversionToBase: 1, salePrice: 25000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "TO2601", expiryInDays: 400, unitName: "Lọ", quantity: 20, unitCost: 18000 }],
  },

  // --- Thực phẩm chức năng ---------------------------------------------------
  {
    ...base,
    code: "TP0010",
    name: "Vitamin 3B (B1-B6-B12)",
    productType: "SUPPLEMENT",
    drugClass: null,
    categoryName: "Thực phẩm chức năng",
    dosageForm: "Viên nang mềm",
    packagingText: "Hộp 10 vỉ x 10 viên",
    manufacturer: "Công ty CP Dược phẩm Nam Hà",
    minStockBaseQuantity: 200,
    vatRatePercent: 8,
    ingredients: [
      { name: "Vitamin B1", strengthText: "100 mg" },
      { name: "Vitamin B6", strengthText: "200 mg" },
      { name: "Vitamin B12", strengthText: "200 mcg" },
    ],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 1500, isDefaultSaleUnit: true },
      { name: "Vỉ", conversionToBase: 10, salePrice: 14000 },
    ],
    batches: [{ batchNumber: "VB2603", expiryInDays: 620, unitName: "Vỉ", quantity: 40, unitCost: 10000 }],
  },
  {
    ...base,
    code: "TP0011",
    name: "Canxi D3 viên sủi",
    productType: "SUPPLEMENT",
    drugClass: null,
    categoryName: "Thực phẩm chức năng",
    dosageForm: "Viên sủi",
    packagingText: "Tuýp 20 viên",
    manufacturer: "Công ty CP Dược phẩm Traphaco",
    minStockBaseQuantity: 40,
    vatRatePercent: 8,
    ingredients: [
      { name: "Calci carbonat", strengthText: "1250 mg" },
      { name: "Vitamin D3", strengthText: "400 IU" },
    ],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 4000, isDefaultSaleUnit: true },
      { name: "Tuýp", conversionToBase: 20, salePrice: 72000 },
    ],
    batches: [{ batchNumber: "CA2602", expiryInDays: 580, unitName: "Tuýp", quantity: 15, unitCost: 54000 }],
  },
  {
    ...base,
    code: "TP0012",
    name: "Dầu cá Omega-3 1000mg",
    productType: "SUPPLEMENT",
    drugClass: null,
    categoryName: "Thực phẩm chức năng",
    dosageForm: "Viên nang mềm",
    packagingText: "Lọ 100 viên",
    manufacturer: "Nature's Bounty",
    countryOfOrigin: "Mỹ",
    minStockBaseQuantity: 100,
    vatRatePercent: 8,
    ingredients: [{ name: "Dầu cá Omega-3", strengthText: "1000 mg" }],
    units: [
      { name: "Viên", conversionToBase: 1, salePrice: 3500, isDefaultSaleUnit: true },
      { name: "Lọ", conversionToBase: 100, salePrice: 320000 },
    ],
    batches: [{ batchNumber: "OM2601", expiryInDays: 660, unitName: "Lọ", quantity: 8, unitCost: 245000 }],
  },
  {
    ...base,
    code: "TP0013",
    name: "Siro kẽm cho trẻ 100ml",
    productType: "SUPPLEMENT",
    drugClass: null,
    categoryName: "Thực phẩm chức năng",
    dosageForm: "Siro",
    packagingText: "Chai 100 ml",
    manufacturer: "Công ty CP Dược phẩm Nam Hà",
    minStockBaseQuantity: 20,
    vatRatePercent: 8,
    ingredients: [{ name: "Kẽm gluconat", strengthText: "70 mg/5 ml" }],
    units: [{ name: "Chai", conversionToBase: 1, salePrice: 75000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "ZN2604", expiryInDays: 520, unitName: "Chai", quantity: 20, unitCost: 55000 }],
  },

  // --- Vật tư y tế và chăm sóc cá nhân --------------------------------------
  {
    ...base,
    code: "DC0010",
    name: "Máy đo huyết áp bắp tay Omron",
    productType: "MEDICAL_DEVICE",
    drugClass: null,
    categoryName: "Vật tư y tế",
    dosageForm: "Thiết bị điện tử",
    packagingText: "Hộp 1 máy",
    manufacturer: "Omron Healthcare",
    countryOfOrigin: "Nhật Bản",
    storageCondition: "Nơi khô ráo, tránh va đập",
    minStockBaseQuantity: 3,
    vatRatePercent: 10,
    ingredients: [],
    units: [{ name: "Cái", conversionToBase: 1, salePrice: 1150000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "OMR2601", expiryInDays: 1460, unitName: "Cái", quantity: 5, unitCost: 890000 }],
  },
  {
    ...base,
    code: "DC0011",
    name: "Bông y tế tiệt trùng 50g",
    productType: "MEDICAL_DEVICE",
    drugClass: null,
    categoryName: "Vật tư y tế",
    dosageForm: "Bông gòn",
    packagingText: "Gói 50 g",
    manufacturer: "Công ty CP Bông Bạch Tuyết",
    minStockBaseQuantity: 40,
    vatRatePercent: 10,
    ingredients: [],
    units: [{ name: "Gói", conversionToBase: 1, salePrice: 12000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "BG2601", expiryInDays: 900, unitName: "Gói", quantity: 60, unitCost: 8000 }],
  },
  {
    ...base,
    code: "DC0012",
    name: "Băng gạc vô trùng 10x10cm",
    productType: "MEDICAL_DEVICE",
    drugClass: null,
    categoryName: "Vật tư y tế",
    dosageForm: "Gạc vô trùng",
    packagingText: "Hộp 10 miếng",
    manufacturer: "Công ty CP Bông Bạch Tuyết",
    minStockBaseQuantity: 50,
    vatRatePercent: 10,
    ingredients: [],
    units: [
      { name: "Miếng", conversionToBase: 1, salePrice: 4000, isDefaultSaleUnit: true },
      { name: "Hộp", conversionToBase: 10, salePrice: 36000 },
    ],
    batches: [{ batchNumber: "GA2602", expiryInDays: 900, unitName: "Hộp", quantity: 20, unitCost: 26000 }],
  },
  {
    ...base,
    code: "DC0013",
    name: "Cồn 70 độ 500ml",
    productType: "DRUG",
    drugClass: "OTC",
    categoryName: "Vật tư y tế",
    dosageForm: "Dung dịch dùng ngoài",
    strengthText: "70 độ",
    packagingText: "Chai 500 ml",
    manufacturer: "Công ty CP Dược phẩm Medipharco",
    storageCondition: "Tránh xa nguồn lửa, nơi thoáng mát",
    minStockBaseQuantity: 30,
    ingredients: [],
    units: [{ name: "Chai", conversionToBase: 1, salePrice: 22000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "CO2601", expiryInDays: 760, unitName: "Chai", quantity: 40, unitCost: 15000 }],
  },
  {
    ...base,
    code: "MP0001",
    name: "Kem chống nắng SPF50+ 50ml",
    productType: "COSMETIC",
    drugClass: null,
    categoryName: "Chăm sóc cá nhân",
    dosageForm: "Kem bôi da",
    packagingText: "Tuýp 50 ml",
    manufacturer: "La Roche-Posay",
    countryOfOrigin: "Pháp",
    minStockBaseQuantity: 10,
    vatRatePercent: 10,
    ingredients: [],
    units: [{ name: "Tuýp", conversionToBase: 1, salePrice: 395000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "KC2602", expiryInDays: 600, unitName: "Tuýp", quantity: 12, unitCost: 290000 }],
  },
  {
    ...base,
    code: "MP0002",
    name: "Sữa rửa mặt dịu nhẹ 236ml",
    productType: "COSMETIC",
    drugClass: null,
    categoryName: "Chăm sóc cá nhân",
    dosageForm: "Sữa rửa mặt",
    packagingText: "Chai 236 ml",
    manufacturer: "Cetaphil",
    countryOfOrigin: "Canada",
    minStockBaseQuantity: 10,
    vatRatePercent: 10,
    ingredients: [],
    units: [{ name: "Chai", conversionToBase: 1, salePrice: 245000, isDefaultSaleUnit: true }],
    batches: [{ batchNumber: "SR2601", expiryInDays: 720, unitName: "Chai", quantity: 10, unitCost: 185000 }],
  },
];
