BEGIN;
ALTER TABLE user_roles ADD COLUMN additional_permissions text[] NOT NULL DEFAULT '{}',
  ADD COLUMN qualification_reference text,
  ADD COLUMN responsible_professional boolean NOT NULL DEFAULT false;
ALTER TABLE user_roles ADD CONSTRAINT professional_lead_store_required CHECK (NOT responsible_professional OR store_id IS NOT NULL);
CREATE UNIQUE INDEX one_professional_lead_per_store ON user_roles(store_id) WHERE responsible_professional;
INSERT INTO audit_logs(action, resource_type, resource_id, "before", reason)
SELECT 'LEGACY_SALES_ROLE_RETIRED', 'user', ur.user_id::text,
 jsonb_build_object('roleCode', r.code, 'storeId', ur.store_id),
 'Vai trò ngừng dùng. Cần kiểm tra chuyên môn trước khi gán Dược sĩ; không tự động nâng quyền.'
FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE r.code='sales_staff';
UPDATE refresh_sessions SET revoked_at=now(), revoked_reason='ROLE_MODEL_CHANGED' WHERE revoked_at IS NULL;
DELETE FROM user_roles WHERE role_id IN (SELECT id FROM roles WHERE code='sales_staff');
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code='sales_staff');
DELETE FROM roles WHERE code='sales_staff';
UPDATE roles SET name='Chủ nhà thuốc, quản lý' WHERE code='admin';
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code='admin');
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='store.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='user.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='settings.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='report.chain';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='catalog.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='catalog.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='price.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='stock.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='stock.cost.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='goods_receipt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='goods_receipt.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='goods_receipt.confirm';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='stock.adjust.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='stock.adjust.approve';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='stock.opening_balance';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='batch.quarantine';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='recall.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='invoice.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='invoice.void';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='sale.discount';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='sale.discount.override';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='return.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='customer.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='customer.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='storage_log.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='report.sales';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='report.inventory';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='audit.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='backup.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='controlled.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='supplier_debt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='supplier_payment.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='loyalty.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='national_sync.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='admin' AND p.code='national_sync.manage';
UPDATE roles SET name='Dược sĩ' WHERE code='pharmacist';
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code='pharmacist');
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='catalog.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='catalog.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='stock.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='goods_receipt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='goods_receipt.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='stock.adjust.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='batch.quarantine';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='invoice.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='invoice.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='sale.prescription_drug';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='sale.discount';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='return.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='prescription.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='prescription.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='customer.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='customer.manage';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='customer.sensitive';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='storage_log.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='storage_log.write';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='report.inventory';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='controlled.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='ai.use';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='pharmacist' AND p.code='national_sync.read';
UPDATE roles SET name='Nhân viên kho' WHERE code='warehouse_staff';
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code='warehouse_staff');
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='catalog.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='stock.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='goods_receipt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='goods_receipt.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='stock.adjust.create';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='storage_log.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='warehouse_staff' AND p.code='storage_log.write';
UPDATE roles SET name='Kiểm toán, chỉ đọc' WHERE code='auditor';
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code='auditor');
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='catalog.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='stock.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='stock.cost.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='goods_receipt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='invoice.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='storage_log.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='report.sales';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='report.inventory';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='report.chain';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='audit.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='controlled.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='supplier_debt.read';
INSERT INTO role_permissions(role_id,permission_code) SELECT r.id,p.code FROM roles r,permissions p WHERE r.code='auditor' AND p.code='national_sync.read';
UPDATE settings SET value=value - 'sales_staff' WHERE key='discountLimitPercent' AND jsonb_typeof(value)='object';
COMMIT;
